### ISSUE TITLE
BUG: default branch is always changed to main even if it wasn't master before the rename.

### ISSUE THREAD

**Issue by elrayle** [mheap/github-default-branch#36]
### Description

The default branch for the repo should only be changed if it was set to master before the rename.  

### Expected

If default branch is set to dev before the rename, it should be set to dev after the rename.
If default branch is set to master before the rename, it should be set to main after the rename.

### Actual

WRONG: If default branch is set to dev before the rename, it is set to main after the rename.
CORRECT: If default branch is set to master before the rename, it is set to main after the rename.

### To Reproduce

* ... Settings -> Branches
* Default branch: dev
* rename repo to main
* ... Settings -> Branches
* Default branch: main

The default branch was changed to main. It should only be updated if the default branch was master before the rename.

**Comment by mheap** [comment]
Hey @elrayle!

Firstly, thanks for the **excellent** bug report.

I believe that this was fixed in version `1.8.0`, published a few days ago. Could you update your version of `github-default-branch` and check if it solves the problem for you?

**Comment by elrayle** [comment]
Confirmed that v1.8.0 fixed this bug.  Thanks!
