### ISSUE TITLE
Copy branch protections

### ISSUE THREAD

**Issue by mheap** [mheap/github-default-branch#4]
If you have any branch protections enabled on your current default branch, these will be lost (in fact, the tool might not work at all).

Proposed workflow:

* Store current branch protections
* Disable branch protections on old default branch
* Enable branch protections on new default branch
* Switch default branch
* Delete old default branch

**Comment by foolip** [comment]
Note that the branch protection rule is a pattern, which I expect is very rarely used, but you should probably fail or warn if the pattern contains a `*`.

**Comment by gr2m** [comment]
Here is what I do in `octokit-plugin-rename-branch`:

https://github.com/gr2m/octokit-plugin-rename-branch/blob/5d3c37439515db9f49f049e28510dc596982cb02/src/rename-branch.ts#L56-L90

The code looks for exact matches and updates it. It does not copy it, as that's out of scope for `octokit-plugin-rename-branch`

**Comment by gr2m** [comment]
Thanks for the shout out :)

I haven't used your CLI yet, but I think you have the feature to keep the previous branch around. So maybe it should not be an update of the pattern, but a copy of the settings?
