### ISSUE TITLE
Preserving URLs

### ISSUE THREAD

**Issue by foolip** [mheap/github-default-branch#6]
The last step of "Delete the old branch" will break existing links including the branch name, which are fairly commonly spread around in at least my line of work (browser vendors). Here's one random example from a repo I work in a lot to illustrate:
https://github.com/web-platform-tests/wpt/commit/1f1d9408d23bbdbb9e0fc2c050b55577814a35c0

Currently, keeping the old branch around is probably the only way to fix this. Better would be automatically redirecting, since the intention of such links was to follow tip-of-tree.

I don't know if GitHub is planning any server-side aliasing to fix this, have you been in touch?

**Comment by mheap** [comment]
I'm unaware of any plans GitHub themselves have to help with this.

You can run with `--keep-old` if you'd like to skip the last step and keep the old branch. Could this be clearer in the documentation?

**Comment by foolip** [comment]
I think it would be good to spell out the implications of deleting the old branch in the documentation, and maybe to ask for confirmation before doing it since it's the default?

**Comment by mheap** [comment]
I can definitely make it clearer in the docs, and make it clear that the old branch has been deleted in the CLI output.

What do you think about a section similar to the following in the README?

---

### Help! It deleted my `$old` branch and I need it

By default this tool deletes the old branch intentionally. If you need to restore the old branch, run the following command on your local machine after cloning the repo:

> The example assumes that you renamed from `master` to `main`

```
git fetch
git push origin remotes/origin/main:refs/heads/master
```

**Comment by foolip** [comment]
Proving instructions for recovering is good, but informing people ahead of time about broken URLs in case they haven't thought about that would be good.

Per https://twitter.com/natfriedman/status/1271253144442253312 there may be some support for branch switching coming from GitHub, so if I were in the position to give people advice I would recommend just waiting for a few weeks. If any kind of redirecting will happen, it's somewhat likely that it won't work if the rename has already happened. (Similar to what happens if you create a new repo instead of moving, and later would like to redirect the old repo to the new.)

**Comment by mheap** [comment]
I can add a `--confirm` flag and if it's not present, prompt for confirmation after explaining the steps that will be taken 👍

**Comment by foolip** [comment]
That sounds good, thanks!
