### ISSUE TITLE
Update README badges

### ISSUE THREAD

**Issue by mathiasbynens** [mheap/github-default-branch#7]
README badges are fairly common, and often refer to the branch name in their URLs:

```
[![Build status](https://travis-ci.org/org/repo.svg?branch=master)](https://travis-ci.org/org/repo)
```

We could probably figure out some patterns like <code><i>org/repo</i>.svg?branch=<i>old_branch_name</i></code> which can be replaced with <code><i>org/repo</i>.svg?branch=<i>new_branch_name</i></code>.

**Comment by mheap** [comment]
Released as 1.4.0
